### ISSUE TITLE
Curveball solution not working

### ISSUE THREAD

**Issue by TolisKoutro** [kenny-420/cryptohack-solutions#1]
[https://github.com/kenny-420/cryptohack-solutions/blob/main/ELLIPTIC-CURVES/14_Curveball.py](url)
Gives an error on line 8

**Comment by kenny-420** [comment]
what's the error

**Comment by TolisKoutro** [comment]
I got it working using python in terminal. I was getting an error while using the Cryptohack docker image. Thank you!
