### ISSUE TITLE
Getting error on RSA 29 Let's Decrypt Again

### ISSUE THREAD

**Issue by TolisKoutro** [kenny-420/cryptohack-solutions#2]
I am trying to run this and I get this error

`[x] Opening connection to socket.cryptohack.org on port 13394
[-] Opening connection to socket.cryptohack.org on port 13394: Failed
---------------------------------------------------------------------------
OSError                                   Traceback (most recent call last)
Cell In [2], line 14
     11 s = Integer(0x910f5f4fd7f0f5408711f577ac68bd24ede89d948681298a29d3d2094d13dbc24872bcaa37ccce91c35366ee2f3dd5324f68d33be48a7f0f10beb280f326fbabe2cc7c2fd343c57212f9aae481192144592338ecd2de2351289c383c1490f0d2)                                                   
     12 n = Integer(1000120007020266767402749898742219793970297020432528956049530793865219680313442335799796740977248798869240976808292142421700982073722069461150446330334899583118911948842763629030864693933380584918689773987802449535745833592107844509736928801)    
---> 14 io = remote('socket.cryptohack.org', Integer(13394))
     15 io.recvline()
     16 io.sendline(dumps({'option': 'set_pubkey', 'pubkey': hex(n)}).encode())

File ~/.sage/local/lib/python3.11/site-packages/pwnlib/tubes/remote.py:77, in remote.__init__(self, host, port, fam, typ, ssl, sock, ssl_context, ssl_args, sni, *args, **kwargs)                                                                                         
     75 fam = self._get_family(fam)
     76 try:
---> 77     self.sock   = self._connect(fam, typ)
     78 except socket.gaierror as e:
     79     if e.errno != socket.EAI_NONAME:

File ~/.sage/local/lib/python3.11/site-packages/pwnlib/tubes/remote.py:103, in remote._connect(self, fam, typ)
    100 timeout = self.timeout
    102 with self.waitfor('Opening connection to %s on port %s' % (self.rhost, self.rport)) as h:
--> 103     for res in socket.getaddrinfo(self.rhost, self.rport, fam, typ, 0, socket.AI_PASSIVE):
    104         self.family, self.type, self.proto, _canonname, sockaddr = res
    106         if self.type not in [socket.SOCK_STREAM, socket.SOCK_DGRAM]:

File /usr/lib/python3.11/socket.py:962, in getaddrinfo(host, port, family, type, proto, flags)
    959 # We override this function since we want to translate the numeric family
    960 # and socket type values to enum constants.
    961 addrlist = []
--> 962 for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
    963     af, socktype, proto, canonname, sa = res
    964     addrlist.append((_intenum_converter(af, AddressFamily),
    965                      _intenum_converter(socktype, SocketKind),
    966                      proto, canonname, sa))

OSError: Int or String expected
`

**Comment by kenny-420** [comment]
fixed, try again now

**Comment by TolisKoutro** [comment]
It works perfectly. Thank you! Also are you planning on uploading more challenges from Cryptohack?

**Comment by kenny-420** [comment]
Yes, soon

**Comment by TolisKoutro** [comment]
Thank you so much!
